export const types = {
  GET_USER_DATA: 'GET_USER_DATA',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',

  GET_CHATID_DATA: 'GET_CHATID_DATA',
  GET_CHATID_SUCCESS: 'GET_CHATID_SUCCESS',
  GET_CHATID_FAILURE: 'GET_CHATID_FAILURE',

  GET_USER2_DATA: 'GET_USER2_DATA',
  GET_USER2_DATA_SUCCESS: 'GET_USER2_DATA_SUCCESS',
  GET_USER2_DATA_FAILURE: 'GET_USER2_DATA_FAILURE',

  GET_CONTACTLISTUSER_DATA: 'GET_CONTACTLISTUSER_DATA',
  GET_CONTACTLISTUSER_DATA_SUCCESS: 'GET_CONTACTLISTUSER_DATA_SUCCESS',
  GET_CONTACTLISTUSER_DATA_FAILURE: 'GET_CONTACTLISTUSER_DATA_FAILURE',

  CREATE_CHATROOM: 'CREATE_CHATROOM',
  CREATE_CHATROOM_SUCCESS: 'CREATE_CHATROOM_SUCCESS',
  CREATE_CHATROOM_FAILURE: 'CREATE_CHATROOM_FAILURE',

  SET_CHATROOM: 'SET_CHATROOM',
  SET_CHATROOM_SUCCESS: 'SET_CHATROOM_SUCCESS',
  SET_CHATROOM_FAILURE: 'SET_CHATROOM_FAILURE',

  SET_USER1_IN_CHATROOM: 'SET_USER1_IN_CHATROOM',
  SET_USER1_IN_CHATROOM_SUCCESS: 'SET_USER1_IN_CHATROOM_SUCCESS',
  SET_USER1_IN_CHATROOM_FAILURE: 'SET_USER1_IN_CHATROOM_FAILURE',

  UPDATE_DOCID_IN_USER1: 'UPDATE_DOCID_IN_USER1',
  UPDATE_DOCID_IN_USER1_SUCCESS: 'UPDATE_DOCID_IN_USER1_SUCCESS',
  UPDATE_DOCID_IN_USER1_FAILURE: 'UPDATE_DOCID_IN_USER1_FAILURE',

  UPDATE_DOCID_IN_USER2: 'UPDATE_DOCID_IN_USER2',
  UPDATE_DOCID_IN_USER2_SUCCESS: 'UPDATE_DOCID_IN_USER2_SUCCESS',
  UPDATE_DOCID_IN_USER2_FAILURE: 'UPDATE_DOCID_IN_USER2_FAILURE',

  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  UPDATE_MESSAGE_SUCCESS: 'UPDATE_MESSAGE_SUCCESS',
  UPDATE_MESSAGE_FAILURE: 'UPDATE_MESSAGE_FAILURE',

  UPDATE_DATA: 'UPDATE_DATA',
  UPDATE_DATA_SUCCESS: 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAILURE: 'UPDATE_DATA_FAILURE',

  USER_SIGNOUT: 'USER_SIGNOUT',
  USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS',
  USER_SIGNOUT_FAILURE: 'USER_SIGNOUT_FAILURE',

  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  CLEAR_MESSAGE_SUCCESS: 'CLEAR_MESSAGE_SUCCESS',
  CLEAR_MESSAGE_FAILURE: 'CLEAR_MESSAGE_FAILURE',

  GET_REALTIME_MESSAGE: 'GET_REALTIME_MESSAGE',
  GET_REALTIME_MESSAGE_SUCCESS: 'GET_REALTIME_MESSAGE_SUCCESS',
  GET_REALTIME_MESSAGE_FAILURE: 'GET_REALTIME_MESSAGE_FAILURE',

  GET_REALTIME_MESSAGE_AFTER_PAGINATION:
    'GET_REALTIME_MESSAGE_AFTER_PAGINATION',
  GET_REALTIME_MESSAGE_AFTER_PAGINATION_SUCCESS:
    'GET_REALTIME_MESSAGE_AFTER_PAGINATION_SUCCESS',
  GET_REALTIME_MESSAGE_AFTER_PAGINATION_FAILURE:
    'GET_REALTIME_MESSAGE_AFTER_PAGINATION_FAILURE',

  CREATE_REALTIME_DATABASE: 'CREATE_REALTIME_DATABASE',
  CREATE_REALTIME_DATABASE_SUCCESS: 'CREATE_REALTIME_DATABASE_SUCCESS',
  CREATE_REALTIME_DATABASE_FAILURE: 'CREATE_REALTIME_DATABASE_FAILURE',

  CLEAR_USER_DATA: 'CLEAR_USER_DATA',
  CLEAR_USER_DATA_SUCCESS: 'CLEAR_USER_DATA_SUCCESS',
  CLEAR_USER_DATA_FAILURE: 'CLEAR_USER_DATA_FAILURE',

  SAVE_CONTACT: 'SAVE_CONTACT',
  SAVE_CONTACT_SUCESS: 'SAVE_CONTACT_SUCESS',
  SAVE_CONTACT_FAILURE: 'SAVE_CONTACT_FAILURE',

  SET_PROFILE_INFO: 'SET_PROFILE_INFO',
  SET_PROFILE_INFO_SUCESS: 'SET_PROFILE_INFO_SUCESS',
  SET_PROFILE_INFO_FAILURE: 'SET_PROFILE_INFO_FAILURE',

  FILTER_CHATSCREEN_DATA: 'FILTER_CHATSCREEN_DATA',
  FILTER_CHATSCREEN_DATA_SUCESS: 'FILTER_CHATSCREEN_DATA_SUCESS',
  FILTER_CHATSCREEN_DATA_FAILURE: 'FILTER_CHATSCREEN_DATA_FAILURE',

  FILTER_CREATENEWSCREEN_DATA: 'FILTER_CREATENEWSCREEN_DATA',
  FILTER_CREATENEWSCREEN_DATA_SUCESS: 'FILTER_CREATENEWSCREEN_DATA_SUCESS',
  FILTER_CREATENEWSCREEN_DATA_FAILURE: 'FILTER_CREATENEWSCREEN_DATA_FAILURE',
};

